# termux plugin manager
[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"
exact = true
[".config/alacritty/colors/challenger_deep.yaml"]
type = "file"
url = "https://raw.githubusercontent.com/eendroroy/alacritty-theme/master/themes/challenger_deep.yaml"
refreshPeriod = "168h"
# Oh my ZSH and plugins
[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
#[".oh-my-zsh/custom/themes/powerlevel10k"]
#type = "archive"
#url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
#exact = true
#stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
url = 'https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz'
type = "archive"
stripComponents = 1
exact = true
[".oh-my-zsh/custom/plugins/zsh-completions"]
url = 'https://github.com/zsh-users/zsh-completions/archive/{{ ( gitHubLatestRelease "zsh-users/zsh-completions").TagName }}.tar.gz'
type = "archive"
stripComponents = 1
exact = true
#zsh plugin to use fzf for tab completion
[".oh-my-zsh/custom/plugins/fzf-tab"]
url = 'https://github.com/Aloxaf/fzf-tab/archive/refs/heads/master.zip'
type = "archive"
stripComponents = 1
exact = true
# Direnv loads env variables from local directories
[".local/bin/direnv"]
type = "file"
url = 'https://github.com/direnv/direnv/releases/download/{{( gitHubLatestRelease "direnv/direnv").TagName }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}'
executable = true
[".config/Lazy"]
type = "git-repo"
url = "https://github.com/danielo515/lazyvim"
