import = ["./keys.yml"]
live_config_reload = true
theme = "Dracula"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Inconsolata Nerd Font Mono"
style = "ExtraLight"

[font.normal]
family = "Inconsolata Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[hints.bright]
black = "#656687"
blue = "#1e90ff"
cyan = "#1e90ff"
green = "#85e89d"
magenta = "#b392f0"
red = "#d54e54"
white = "#f6f8fa"
yellow = "#ffea7f"

[hints.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#cecece"
yellow = "#9e824c"

[hints.normal]
blue = "#0fc9e4"
cyan = "#73e3ff"
green = "#59e858"
magenta = "#b392f0"
white = "#666666"
yellow = "#ffea7f"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002)"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1.0
option_as_alt = "Both"

[window.position]
x = 550
y = 0
[window.dimensions]
columns = 200
lines = 300
