# Alacritty
# https://github.com/alacritty/alacritty
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#
# Documents:
#
# Fix keyboard input on terminals: http://www.leonerd.org.uk/hacks/fixterms/
# Key names: https://docs.rs/glutin/latest/glutin/event/enum.VirtualKeyCode.html
#
# Useful commands to get code-points and key names:
#
# showkey --ascii
# alacritty --print-events
[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "H"
mods = "Control"
chars = "\u001b[104;5u"

[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001b[105;5u"

[[keyboard.bindings]]
key = "J"
mods = "Control"
chars = "\u001b[106;5u"

[[keyboard.bindings]]
key = "M"
mods = "Control"
chars = "\u001b[109;5u"

[[keyboard.bindings]]
key = "A"
mods = "Control|Shift"
chars = "\u001b[65;6u"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
chars = "\u001b[68;6u"

[[keyboard.bindings]]
key = "E"
mods = "Control|Shift"
chars = "\u001b[69;6u"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
chars = "\u001b[71;6u"

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;6u"

[[keyboard.bindings]]
key = "I"
mods = "Control|Shift"
chars = "\u001b[73;6u"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;6u"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;6u"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;6u"

[[keyboard.bindings]]
key = "M"
mods = "Control|Shift"
chars = "\u001b[77;6u"

[[keyboard.bindings]]
key = "O"
mods = "Control|Shift"
chars = "\u001b[79;6u"

[[keyboard.bindings]]
key = "P"
mods = "Control|Shift"
chars = "\u001b[80;6u"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
chars = "\u001b[81;6u"

[[keyboard.bindings]]
key = "R"
mods = "Control|Shift"
chars = "\u001b[82;6u"

[[keyboard.bindings]]
key = "S"
mods = "Control|Shift"
chars = "\u001b[83;6u"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u001b[84;6u"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u001b[87;6u"

[[keyboard.bindings]]
key = "X"
mods = "Control|Shift"
chars = "\u001b[88;6u"

[[keyboard.bindings]]
key = "Y"
mods = "Control|Shift"
chars = "\u001b[89;6u"

[[keyboard.bindings]]
key = "Z"
mods = "Control|Shift"
chars = "\u001b[90;6u"

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[49;5u"

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[50;5u"

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[51;5u"

[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[52;5u"

[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[53;5u"

[[keyboard.bindings]]
key = "Key6"
mods = "Control"
chars = "\u001b[54;5u"

[[keyboard.bindings]]
key = "Key7"
mods = "Control"
chars = "\u001b[55;5u"

[[keyboard.bindings]]
key = "Key8"
mods = "Control"
chars = "\u001b[56;5u"

[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b[57;5u"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
chars = "\u001b[48;6u"

[[keyboard.bindings]]
key = "Key1"
mods = "Control|Shift"
chars = "\u001b[49;6u"

[[keyboard.bindings]]
key = "Key2"
mods = "Control|Shift"
chars = "\u001b[50;6u"

[[keyboard.bindings]]
key = "Key3"
mods = "Control|Shift"
chars = "\u001b[51;6u"

[[keyboard.bindings]]
key = "Key4"
mods = "Control|Shift"
chars = "\u001b[52;6u"

[[keyboard.bindings]]
key = "Key5"
mods = "Control|Shift"
chars = "\u001b[53;6u"

[[keyboard.bindings]]
key = "Key6"
mods = "Control|Shift"
chars = "\u001b[54;6u"

[[keyboard.bindings]]
key = "Key7"
mods = "Control|Shift"
chars = "\u001b[55;6u"

[[keyboard.bindings]]
key = "Key8"
mods = "Control|Shift"
chars = "\u001b[56;6u"

[[keyboard.bindings]]
key = "Key9"
mods = "Control|Shift"
chars = "\u001b[57;6u"

[[keyboard.bindings]]
key = "A"
mods = "Alt|Shift"
chars = "\u001bA"

[[keyboard.bindings]]
key = "B"
mods = "Alt|Shift"
chars = "\u001bB"

[[keyboard.bindings]]
key = "C"
mods = "Alt|Shift"
chars = "\u001bC"

[[keyboard.bindings]]
key = "D"
mods = "Alt|Shift"
chars = "\u001bD"

[[keyboard.bindings]]
key = "E"
mods = "Alt|Shift"
chars = "\u001bE"

[[keyboard.bindings]]
key = "F"
mods = "Alt|Shift"
chars = "\u001bF"

[[keyboard.bindings]]
key = "G"
mods = "Alt|Shift"
chars = "\u001bG"

[[keyboard.bindings]]
key = "H"
mods = "Alt|Shift"
chars = "\u001bH"

[[keyboard.bindings]]
key = "I"
mods = "Alt|Shift"
chars = "\u001bI"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
chars = "\u001bJ"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
chars = "\u001bK"

[[keyboard.bindings]]
key = "L"
mods = "Alt|Shift"
chars = "\u001bL"

[[keyboard.bindings]]
key = "M"
mods = "Alt|Shift"
chars = "\u001bM"

[[keyboard.bindings]]
key = "N"
mods = "Alt|Shift"
chars = "\u001bN"

[[keyboard.bindings]]
key = "O"
mods = "Alt|Shift"
chars = "\u001bO"

[[keyboard.bindings]]
key = "P"
mods = "Alt|Shift"
chars = "\u001bP"

[[keyboard.bindings]]
key = "Q"
mods = "Alt|Shift"
chars = "\u001bQ"

[[keyboard.bindings]]
key = "R"
mods = "Alt|Shift"
chars = "\u001bR"

[[keyboard.bindings]]
key = "S"
mods = "Alt|Shift"
chars = "\u001bS"

[[keyboard.bindings]]
key = "T"
mods = "Alt|Shift"
chars = "\u001bT"

[[keyboard.bindings]]
key = "U"
mods = "Alt|Shift"
chars = "\u001bU"

[[keyboard.bindings]]
key = "V"
mods = "Alt|Shift"
chars = "\u001bV"

[[keyboard.bindings]]
key = "W"
mods = "Alt|Shift"
chars = "\u001bW"

[[keyboard.bindings]]
key = "X"
mods = "Alt|Shift"
chars = "\u001bX"

[[keyboard.bindings]]
key = "Y"
mods = "Alt|Shift"
chars = "\u001bY"

[[keyboard.bindings]]
key = "Z"
mods = "Alt|Shift"
chars = "\u001bZ"

[[keyboard.bindings]]
key = "Key0"
mods = "Alt"
chars = "\u001b0"

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
chars = "\u001b1"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
chars = "\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
chars = "\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"
chars = "\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
chars = "\u001b5"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
chars = "\u001b6"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
chars = "\u001b7"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
chars = "\u001b8"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
chars = "\u001b9"

# [[keyboard.bindings]]
# key = "Grave"
# mods = "Alt"
# chars = "\u001b`"

[[keyboard.bindings]]
key = "Minus"
mods = "Alt"
chars = "\u001b-"

[[keyboard.bindings]]
key = "Equals"
mods = "Alt"
chars = "\u001b="

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt"
chars = "\u001b["

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt"
chars = "\u001b]"

[[keyboard.bindings]]
key = "Backslash"
mods = "Alt"
chars = "\u001b\\"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Alt"
chars = "\u001b;"

# [[keyboard.bindings]]
# key = "Apostrophe"
# mods = "Alt"
# chars = "\u001b'"

[[keyboard.bindings]]
key = "Comma"
mods = "Alt"
chars = "\u001b,"

[[keyboard.bindings]]
key = "Period"
mods = "Alt"
chars = "\u001b."

[[keyboard.bindings]]
key = "Slash"
mods = "Alt"
chars = "\u001b/"

# [[keyboard.bindings]]
# key = "Grave"
# mods = "Alt|Shift"
# chars = "\u001b~"

[[keyboard.bindings]]
key = "Key1"
mods = "Alt|Shift"
chars = "\u001b!"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt|Shift"
chars = "\u001b@"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt|Shift"
chars = "\u001b#"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt|Shift"
chars = "\u001b$"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt|Shift"
chars = "\u001b%"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt|Shift"
chars = "\u001b^"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt|Shift"
chars = "\u001b&"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt|Shift"
chars = "\u001b*"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt|Shift"
chars = "\u001b("

[[keyboard.bindings]]
key = "Key0"
mods = "Alt|Shift"
chars = "\u001b)"

[[keyboard.bindings]]
key = "Minus"
mods = "Alt|Shift"
chars = "\u001b_"

[[keyboard.bindings]]
key = "Equals"
mods = "Alt|Shift"
chars = "\u001b+"

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt|Shift"
chars = "\u001b{"

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt|Shift"
chars = "\u001b}"

[[keyboard.bindings]]
key = "Backslash"
mods = "Alt|Shift"
chars = "\u001b|"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Alt|Shift"
chars = "\u001b:"

[[keyboard.bindings]]
key = "Comma"
mods = "Alt|Shift"
chars = "\u001b<"

[[keyboard.bindings]]
key = "Period"
mods = "Alt|Shift"
chars = "\u001b>"

[[keyboard.bindings]]
key = "Slash"
mods = "Alt|Shift"
chars = "\u001b?"
