name: haxe-nvim

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run:  "echo TODO: do any adjust"
      - name: Pushes to haxe-nvim repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_API_TOKEN }}
        with:
          source-directory: 'danielo_nvim'
          destination-github-username: 'danielo515'
          destination-repository-name: 'haxe-nvim'
          user-email: rdanielo@gmail.com
          target-branch: master
