name: CI-dots
on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    # note: this will keep updating the existing branch
    - cron: "*/15 10-14 * * 0,6"
    - cron: "0 14 * * 1-5"
jobs:
  unixish:
    name: ${{ matrix.os }} ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            os: linux
          - runner: macos-12
            os: osx
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- -b $$HOME/bin --source $GITHUB_WORKSPACE
      - name: Install neovim binary
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.8.1
      - name: Install LunarVim stable
        timeout-minutes: 15
        run: |
         LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) -s -- -n
      - name: Apply my config
        timeout-minutes: 1
        run: $HOME/bin/chezmoi apply     
      - name: run lvim!
        timeout-minutes: 1
        run: $HOME/.local/bin/lvim -Es -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

